import turtle
wn=turtle.Screen()
t=turtle.Turtle()

turtle.bgcolor("red")
t.pensize(5)
t.fillcolor("white")
t.color("white")
t.begin_fill
for i in range(1):
  t.forward(240)
  t.stamp()
  t.backward(240)
  t.left(16)
  t.forward(300)
  t.stamp()
  t.backward(300)
  t.left(16)
  t.forward(340)
  t.stamp()
  t.backward(340)
  t.left(16)
  t.forward(300)
  t.stamp()
  t.backward(300)
  t.left(16)
  t.forward(240)
  t.stamp()
  t.backward(240)
  t.left(16)
  t.forward(190)
  t.stamp()
  t.backward(190)
t.end_fill()
wn.exitonclick()
